In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
print("done")


done


In [2]:
df = pd.read_csv("variables.csv")
df.head()

Unnamed: 0  Total_Days  amount_raised_usd  amount_raised_usd_boxcox  state  \
0           0          21              840.0                  5.514380      0   
1           1          22              250.0                  4.682444      0   
2           2          22              200.0                  4.522399      0   
3           3          30              500.0                  5.165823      0   
4           4         120              360.0                  4.939299      0   

  currency        category  month_launch  
0      USD  Transportation             4  
1      USD    Human Rights             6  
2      USD    Human Rights             6  
3      USD     Photography             9  
4      USD    Human Rights             9

In [3]:
df = df.drop(['Unnamed: 0'],axis=1)
df.head()

Total_Days  amount_raised_usd  amount_raised_usd_boxcox  state currency  \
0          21              840.0                  5.514380      0      USD   
1          22              250.0                  4.682444      0      USD   
2          22              200.0                  4.522399      0      USD   
3          30              500.0                  5.165823      0      USD   
4         120              360.0                  4.939299      0      USD   

         category  month_launch  
0  Transportation             4  
1    Human Rights             6  
2    Human Rights             6  
3     Photography             9  
4    Human Rights             9

In [4]:
df_x = df[['Total_Days','currency','category','month_launch']]
df_x.head()

Total_Days currency        category  month_launch
0          21      USD  Transportation             4
1          22      USD    Human Rights             6
2          22      USD    Human Rights             6
3          30      USD     Photography             9
4         120      USD    Human Rights             9

In [5]:
df_y = df[['amount_raised_usd_boxcox','state']]
df_y.head()

amount_raised_usd_boxcox  state
0                  5.514380      0
1                  4.682444      0
2                  4.522399      0
3                  5.165823      0
4                  4.939299      0

In [7]:
df_x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20618 entries, 0 to 20617
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Total_Days    20618 non-null  int64 
 1   currency      20618 non-null  object
 2   category      20618 non-null  object
 3   month_launch  20618 non-null  int64 
dtypes: int64(2), object(2)
memory usage: 644.4+ KB


In [10]:
# change datatype to object
df_x['Total_Days'] = df_x['Total_Days'].astype('object')
df_x['month_launch'] = df_x['month_launch'].astype('object')
df_x.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20618 entries, 0 to 20617
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Total_Days    20618 non-null  object
 1   currency      20618 non-null  object
 2   category      20618 non-null  object
 3   month_launch  20618 non-null  object
dtypes: object(4)
memory usage: 644.4+ KB


C:\Users\user\AppData\Local\Temp/ipykernel_14644/3731613051.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_x['Total_Days'] = df_x['Total_Days'].astype('object')
C:\Users\user\AppData\Local\Temp/ipykernel_14644/3731613051.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_x['month_launch'] = df_x['month_launch'].astype('object')


In [11]:
label = LabelEncoder()
x_col = df_x.columns
x_col


Index(['Total_Days', 'currency', 'category', 'month_launch'], dtype='object')

In [12]:
for col in x_col:
    df_x[col] = label.fit_transform(df_x[col])

C:\Users\user\AppData\Local\Temp/ipykernel_14644/1092175130.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_x[col] = label.fit_transform(df_x[col])


In [13]:
df_x.head()

Total_Days  currency  category  month_launch
0          21        10        22             3
1          22        10        14             5
2          22        10        14             5
3          30        10        18             8
4          96        10        14             8

In [14]:
df_x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20618 entries, 0 to 20617
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Total_Days    20618 non-null  int32
 1   currency      20618 non-null  int32
 2   category      20618 non-null  int32
 3   month_launch  20618 non-null  int32
dtypes: int32(4)
memory usage: 322.3 KB


In [19]:
df_x.Total_Days.unique()

array([ 21,  22,  30,  96,  42,  60,  92,  63,  75,  59,  66,  86,  15,
        56,  65,  48,  31,  28,  83,  32,  90,  58,  18,  41,  85,  98,
        51,  70,  50,  23,  52,  64,  26,  61,  40,  91,  29,  78,  55,
        24,  35,  46,  69,  20,  43,  45,  97,   0,   6,  11,  44,   3,
        99,  19,  53,  39,  17,  49,  12,  84,  10,  95,  38,  37, 100,
         8,  25,  73,  13,  89,  68,  47,  33,  34,  14,  16,  93,  57,
        88,  71,   9,  27,  94,   5,  54,   7,  36,  77,  80,   1,  67,
         4,   2, 106,  87, 103, 102,  76, 105, 104,  79,  82,  72,  74,
       101,  81,  62])

In [20]:
df_x.currency.unique()

array([10,  4,  1,  5,  0,  6,  8,  2,  9,  3,  7])

In [22]:
df_x.category.unique()

array([22, 14, 18,  2, 26, 20,  1, 21,  7, 19,  4,  9, 15, 17,  5,  8, 24,
       13, 16, 12,  6,  0, 27,  3, 11, 23, 10, 25])

In [23]:
df_x.month_launch.unique()

array([ 3,  5,  8, 10, 11,  0,  1,  2,  4,  6,  7,  9])